import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedRectangle30Widget8.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedRectangle2Widget8.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedDISCOUNT5Widget.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedGroup40Widget11.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedGroup39Widget11.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedGroup43Widget10.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedDISCOUNT10Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedRectangle3Widget18.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedGroup45Widget4.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedDISCOUNTWidget.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedDISCOUNT10Widget.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedGroup41Widget11.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget1/generated/GeneratedGroup44Widget10.dart';

/* Frame Promo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPromoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 60.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 20.0,
                child: GeneratedRectangle2Widget8(),
              ),
              Positioned(
                left: 20.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 19.0,
                child: GeneratedDISCOUNT5Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 19.0,
                child: GeneratedDISCOUNT10Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 19.0,
                child: GeneratedDISCOUNT10Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 22.0,
                child: GeneratedDISCOUNTWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget11(),
              ),
              Positioned(
                left: 20.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget11(),
              ),
              Positioned(
                left: 20.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget11(),
              ),
              Positioned(
                left: 20.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget10(),
              ),
              Positioned(
                left: 20.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget10(),
              ),
              Positioned(
                left: 20.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup45Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget18(),
              ),
              Positioned(
                left: 320.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle30Widget8(),
              )
            ]),
      ),
    ));
  }
}
