import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedBatalWidget4.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedNoTeleponWidget2.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedEmailWidget12.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedRectangle27Widget15.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedPasswordWidget5.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedRectangle29Widget5.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedDAFTARWidget2.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedRectangle1Widget10.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedRectangle28Widget5.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedRectangle27Widget14.dart';
import 'package:flutterapp/mobileapp/generateddaftarwidget4/generated/GeneratedLoginWidget4.dart';

/* Frame Daftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftarWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 59.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 24.0,
                child: GeneratedPasswordWidget5(),
              ),
              Positioned(
                left: 30.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle27Widget14(),
              ),
              Positioned(
                left: 30.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle27Widget15(),
              ),
              Positioned(
                left: 30.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 30.0,
                child: GeneratedRectangle28Widget5(),
              ),
              Positioned(
                left: 78.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 26.0,
                child: GeneratedBatalWidget4(),
              ),
              Positioned(
                left: 190.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 30.0,
                child: GeneratedRectangle29Widget5(),
              ),
              Positioned(
                left: 237.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedLoginWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle1Widget10(),
              ),
              Positioned(
                left: 30.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 26.0,
                child: GeneratedDAFTARWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 6.0,
                child: GeneratedEmailWidget12(),
              ),
              Positioned(
                left: 30.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 24.0,
                child: GeneratedNoTeleponWidget2(),
              )
            ]),
      ),
    ));
  }
}
