import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedGroup39Widget4.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedGroup40Widget4.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedRectangle3Widget8.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedGroup41Widget4.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedGroup43Widget3.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedGroup44Widget3.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget/generated/GeneratedRectangle10Widget10.dart';

/* Frame Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 714.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 190.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget8(),
              ),
              Positioned(
                left: 60.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 20.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 278.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedRectangle56Widget(),
              ),
              Positioned(
                left: 321.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget10(),
              )
            ]),
      ),
    ));
  }
}
