import 'package:flutter/material.dart';

/* Text Ruang Tamu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRuangTamuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Ruang Tamu''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2102272510528564,
        fontSize: 12.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 165, 190, 204),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
