import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRp1370000Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedUnitlaciputih36x70cmWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedALEXWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedPetunjukPerawatanWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle10Widget6.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedPilihWidget.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle10Widget7.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle10Widget5.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedBeliSekarangWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle10Widget9.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle3Widget4.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRincianProdukWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget/generated/GeneratedRectangle10Widget8.dart';

/* Frame Pilih Warna Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPilihWarnaProdukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 819.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 24.0,
                child: GeneratedRp1370000Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 32.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 250.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget5(),
              ),
              Positioned(
                left: 43.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget6(),
              ),
              Positioned(
                left: 65.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget7(),
              ),
              Positioned(
                left: 87.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget8(),
              ),
              Positioned(
                left: 110.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget9(),
              ),
              Positioned(
                left: 104.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 21.0,
                child: GeneratedBeliSekarangWidget1(),
              ),
              Positioned(
                left: 302.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 28.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedRincianProdukWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 87.0,
                child:
                    GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla1(),
              ),
              Positioned(
                left: 20.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedALEXWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 20.0,
                child: GeneratedUnitlaciputih36x70cmWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 53.0,
                child:
                    GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa1(),
              ),
              Positioned(
                left: 21.0,
                top: 717.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 20.0,
                child: GeneratedPetunjukPerawatanWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 100.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle47Widget(),
              ),
              Positioned(
                left: 81.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 25.0,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 22.0,
                child: GeneratedPilihWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget4(),
              )
            ]),
      ),
    ));
  }
}
