import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedRectangle3Widget22.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedRectangle1Widget9.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedGroup43Widget12.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedGroup40Widget13.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedGroup44Widget12.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedGroup41Widget13.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedRectangle2Widget10.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedGroup39Widget13.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget2/generated/GeneratedGroup45Widget5.dart';

/* Frame Hasil Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHasilSearchWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 610.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 20.0,
                child: GeneratedRectangle2Widget10(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle1Widget9(),
              ),
              Positioned(
                left: 20.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget12(),
              ),
              Positioned(
                left: 20.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget12(),
              ),
              Positioned(
                left: 20.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup45Widget5(),
              ),
              Positioned(
                left: 321.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget22(),
              )
            ]),
      ),
    ));
  }
}
