import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedGroup51Widget2.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle30Widget9.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle14Widget5.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedLine3Widget4.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedLine3Widget3.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRp1370000Widget4.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedUnitlaciputih36x70cmWidget4.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedPRODUKWidget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedALEXWidget4.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle3Widget19.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedLine4Widget3.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedLokasiBarangWidget2.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedGroup55Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedLine6Widget3.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedPengirimsedangmempersiapkanpesananandaWidget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedPengirimsedangmempersiapkanpesananandaWidget.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedGroup56Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedPengirimsedangmempersiapkanpesananandaWidget4.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedPengirimsedangmempersiapkanpesananandaWidget3.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedGroup54Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedEllipse5Widget2.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedGroup52Widget3.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedGroup53Widget1.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedLine4Widget4.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedPengirimsedangmempersiapkanpesananandaWidget2.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle9Widget6.dart';
import 'package:flutterapp/mobileapp/generatedratingwidget/generated/GeneratedRectangle10Widget17.dart';

/* Frame Rating
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRatingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 840.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 23.0,
                child: GeneratedLokasiBarangWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget19(),
              ),
              Positioned(
                left: 26.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse5Widget2(),
              ),
              Positioned(
                left: 26.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse3Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEllipse4Widget1(),
              ),
              Positioned(
                left: 38.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 1.0,
                child: GeneratedLine3Widget3(),
              ),
              Positioned(
                left: 38.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 1.0,
                child: GeneratedLine5Widget1(),
              ),
              Positioned(
                left: 44.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 1.0,
                child: GeneratedLine4Widget3(),
              ),
              Positioned(
                left: 44.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 1.0,
                child: GeneratedLine6Widget3(),
              ),
              Positioned(
                left: 38.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 1.0,
                child: GeneratedLine3Widget4(),
              ),
              Positioned(
                left: 44.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 1.0,
                child: GeneratedLine4Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 6.0,
                height: 38.0,
                child: GeneratedGroup51Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 250.0,
                child: GeneratedRectangle9Widget6(),
              ),
              Positioned(
                left: 28.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedPRODUKWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 24.0,
                child: GeneratedRp1370000Widget4(),
              ),
              Positioned(
                left: 21.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedALEXWidget4(),
              ),
              Positioned(
                left: 21.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 20.0,
                child: GeneratedUnitlaciputih36x70cmWidget4(),
              ),
              Positioned(
                left: 66.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 34.0,
                child: GeneratedPengirimsedangmempersiapkanpesananandaWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 34.0,
                child: GeneratedPengirimsedangmempersiapkanpesananandaWidget1(),
              ),
              Positioned(
                left: 66.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 34.0,
                child: GeneratedPengirimsedangmempersiapkanpesananandaWidget2(),
              ),
              Positioned(
                left: 66.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 34.0,
                child: GeneratedPengirimsedangmempersiapkanpesananandaWidget3(),
              ),
              Positioned(
                left: 66.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 34.0,
                child: GeneratedPengirimsedangmempersiapkanpesananandaWidget4(),
              ),
              Positioned(
                left: 286.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedGroup52Widget3(),
              ),
              Positioned(
                left: 286.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedGroup53Widget1(),
              ),
              Positioned(
                left: 286.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedGroup56Widget1(),
              ),
              Positioned(
                left: 286.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedGroup54Widget1(),
              ),
              Positioned(
                left: 286.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedGroup55Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle10Widget17(),
              ),
              Positioned(
                left: 51.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 83.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle14Widget5(),
              ),
              Positioned(
                left: 320.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle30Widget9(),
              )
            ]),
      ),
    ));
  }
}
