import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget3/generated/GeneratedRectangle2Widget9.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget3/generated/GeneratedRectangle3Widget21.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget3/generated/GeneratedGroup50Widget3.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget3/generated/GeneratedGroup37Widget2.dart';

/* Frame Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 706.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 20.0,
                child: GeneratedRectangle2Widget9(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.00000762939453,
                height: 30.0,
                child: GeneratedGroup37Widget2(),
              ),
              Positioned(
                left: 321.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget21(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 638.0,
                child: GeneratedGroup50Widget3(),
              )
            ]),
      ),
    ));
  }
}
