import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedTransferWidget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedPEMBAYARANWidget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedLanjutWidget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/mobileapp/generatedtransaksiwidget/generated/GeneratedRectangle3Widget6.dart';

/* Frame Transaksi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTransaksiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 310.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 310.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle42Widget(),
              ),
              Positioned(
                left: 310.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 260.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 20.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 22.0,
                child: GeneratedPEMBAYARANWidget(),
              ),
              Positioned(
                left: 280.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 21.0,
                child: GeneratedLanjutWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 21.0,
                child: GeneratedTransferWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget6(),
              )
            ]),
      ),
    ));
  }
}
