import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle10Widget4.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedPetunjukPerawatanWidget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedBeliSekarangWidget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedALEXWidget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedUnitlaciputih36x70cmWidget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRp1370000Widget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle10Widget3.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRincianProdukWidget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget/generated/GeneratedRectangle10Widget.dart';

/* Frame Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProdukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 704.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 24.0,
                child: GeneratedRp1370000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 32.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 250.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget2(),
              ),
              Positioned(
                left: 87.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget3(),
              ),
              Positioned(
                left: 110.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget4(),
              ),
              Positioned(
                left: 104.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 21.0,
                child: GeneratedBeliSekarangWidget(),
              ),
              Positioned(
                left: 302.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 28.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedRincianProdukWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 87.0,
                child:
                    GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla(),
              ),
              Positioned(
                left: 20.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedALEXWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 20.0,
                child: GeneratedUnitlaciputih36x70cmWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 631.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 53.0,
                child:
                    GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa(),
              ),
              Positioned(
                left: 21.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 20.0,
                child: GeneratedPetunjukPerawatanWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget3(),
              )
            ]),
      ),
    ));
  }
}
