import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/Generated0100Widget.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/GeneratedRectangle32Widget1.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/GeneratedVERIFIKASIKODEWidget.dart';
import 'package:flutterapp/mobileapp/generatedverifikasicodewidget/generated/GeneratedRectangle33Widget1.dart';

/* Frame Verifikasi Code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerifikasiCodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 112.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedRectangle31Widget1(),
              ),
              Positioned(
                left: 62.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 162.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedRectangle32Widget1(),
              ),
              Positioned(
                left: 211.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedRectangle33Widget1(),
              ),
              Positioned(
                left: 261.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 23.0,
                child: GeneratedVERIFIKASIKODEWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle1Widget7(),
              ),
              Positioned(
                left: 62.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 21.0,
                child: Generated0100Widget(),
              )
            ]),
      ),
    ));
  }
}
