import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedRectangle63Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedRectangle55Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedRectangle62Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedLine13Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedGroup50Widget2.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedKategoriWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedDiskonWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedLine15Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedGroup37Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedEllipse6Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedRectangle61Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedOrderanWidget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedLine14Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedLokasiBarangWidget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedRectangle3Widget15.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedLine12Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedRectangle2Widget6.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget1/generated/GeneratedADMIN1Widget.dart';

/* Frame Pengaturan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPengaturanWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 706.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 20.0,
                child: GeneratedRectangle2Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.00000762939453,
                height: 30.0,
                child: GeneratedGroup37Widget1(),
              ),
              Positioned(
                left: 321.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget15(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 638.0,
                child: GeneratedGroup50Widget2(),
              ),
              Positioned(
                left: -12.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 706.0,
                child: GeneratedRectangle55Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 15.0,
                child: GeneratedRectangle62Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 17.0,
                child: GeneratedADMIN1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedEllipse6Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 20.0,
                child: GeneratedRectangle61Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 23.0,
                child: GeneratedKategoriWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 20.0,
                child: GeneratedLokasiBarangWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 23.0,
                child: GeneratedDiskonWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 23.0,
                child: GeneratedOrderanWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 1.0,
                child: GeneratedLine12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 1.0,
                child: GeneratedLine13Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 210.00238037109375,
                height: 1.0,
                child: GeneratedLine14Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 211.0023651123047,
                height: 1.0,
                child: GeneratedLine15Widget1(),
              ),
              Positioned(
                left: 170.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle63Widget1(),
              )
            ]),
      ),
    ));
  }
}
