import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedRectangle3Widget9.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedGroup44Widget4.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedGroup43Widget4.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedGroup45Widget1.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedKURSIWidget.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedGroup39Widget5.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedGroup41Widget5.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedGroup40Widget5.dart';
import 'package:flutterapp/mobileapp/generatedhasilsearchwidget/generated/GeneratedRectangle56Widget1.dart';

/* Frame Hasil Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHasilSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 641.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget5(),
              ),
              Positioned(
                left: 21.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget5(),
              ),
              Positioned(
                left: 21.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget5(),
              ),
              Positioned(
                left: 21.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget4(),
              ),
              Positioned(
                left: 21.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget4(),
              ),
              Positioned(
                left: 21.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup45Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 22.0,
                child: GeneratedKURSIWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 20.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: 306.25,
                top: 29.0,
                right: null,
                bottom: null,
                width: 13.5,
                height: 12.0,
                child: GeneratedRectangle56Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget9(),
              )
            ]),
      ),
    ));
  }
}
