import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedRectangle56Widget4.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedGroup40Widget14.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedGroup43Widget13.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedRectangle4Widget6.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedGroup39Widget14.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedGroup41Widget14.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedRectangle10Widget28.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedRectangle2Widget11.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedGroup44Widget13.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget4/generated/GeneratedRectangle3Widget23.dart';

/* Frame Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 714.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 190.0,
                child: GeneratedRectangle4Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget14(),
              ),
              Positioned(
                left: 20.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget14(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget14(),
              ),
              Positioned(
                left: 20.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget23(),
              ),
              Positioned(
                left: 60.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 20.0,
                child: GeneratedRectangle2Widget11(),
              ),
              Positioned(
                left: 278.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedRectangle56Widget4(),
              ),
              Positioned(
                left: 321.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget28(),
              )
            ]),
      ),
    ));
  }
}
