import 'package:flutter/material.dart';

/* UndefinedNode No.Tlp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoTlpWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
