import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedBeliSekarangWidget3.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle47Widget2.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle30Widget10.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle10Widget21.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle46Widget2.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla2.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa2.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedALEXWidget5.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle3Widget20.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle10Widget19.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle10Widget22.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle48Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle49Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedPilihWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle9Widget7.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle10Widget20.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedPRODUKWidget2.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRp1370000Widget5.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle10Widget18.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedUnitlaciputih36x70cmWidget5.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedPetunjukPerawatanWidget4.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRincianProdukWidget4.dart';
import 'package:flutterapp/mobileapp/generatedpilihwarnaprodukwidget1/generated/GeneratedRectangle14Widget6.dart';

/* Frame Pilih Warna Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPilihWarnaProdukWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 840.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 24.0,
                child: GeneratedRp1370000Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 32.0,
                child: GeneratedRectangle14Widget6(),
              ),
              Positioned(
                left: 39.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 250.0,
                child: GeneratedRectangle9Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget18(),
              ),
              Positioned(
                left: 43.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget19(),
              ),
              Positioned(
                left: 65.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget20(),
              ),
              Positioned(
                left: 87.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget21(),
              ),
              Positioned(
                left: 110.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget22(),
              ),
              Positioned(
                left: 104.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 21.0,
                child: GeneratedBeliSekarangWidget3(),
              ),
              Positioned(
                left: 302.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 28.0,
                child: GeneratedRectangle15Widget3(),
              ),
              Positioned(
                left: 21.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedRincianProdukWidget4(),
              ),
              Positioned(
                left: 21.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 87.0,
                child:
                    GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla2(),
              ),
              Positioned(
                left: 20.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedALEXWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 20.0,
                child: GeneratedUnitlaciputih36x70cmWidget5(),
              ),
              Positioned(
                left: 21.0,
                top: 773.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 53.0,
                child:
                    GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa2(),
              ),
              Positioned(
                left: 21.0,
                top: 743.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 20.0,
                child: GeneratedPetunjukPerawatanWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 100.0,
                child: GeneratedRectangle46Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle47Widget2(),
              ),
              Positioned(
                left: 81.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle48Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 25.0,
                child: GeneratedRectangle49Widget1(),
              ),
              Positioned(
                left: 56.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 22.0,
                child: GeneratedPilihWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget20(),
              ),
              Positioned(
                left: 320.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle30Widget10(),
              ),
              Positioned(
                left: 28.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedPRODUKWidget2(),
              )
            ]),
      ),
    ));
  }
}
