import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedRectangle27Widget10.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedLoginWidget3.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedRectangle28Widget4.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedBatalWidget3.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedRectangle29Widget4.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedLupaKataSandiWidget.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedRectangle27Widget9.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedNamaWidget1.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget2/generated/GeneratedPasswordWidget4.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 24.0,
                child: GeneratedNamaWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle27Widget9(),
              ),
              Positioned(
                left: 30.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle27Widget10(),
              ),
              Positioned(
                left: 30.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 24.0,
                child: GeneratedPasswordWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 30.0,
                child: GeneratedRectangle28Widget4(),
              ),
              Positioned(
                left: 190.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 30.0,
                child: GeneratedRectangle29Widget4(),
              ),
              Positioned(
                left: 237.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedLoginWidget3(),
              ),
              Positioned(
                left: 79.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 26.0,
                child: GeneratedBatalWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 30.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 26.0,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 118.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 21.0,
                child: GeneratedLupaKataSandiWidget(),
              )
            ]),
      ),
    ));
  }
}
