import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedRectangle30Widget6.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedRectangle2Widget7.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedPESANANWidget.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedGroup39Widget10.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedRectangle3Widget16.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedGroup41Widget10.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedGroup43Widget9.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedGroup40Widget10.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedGroup44Widget9.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget2/generated/GeneratedGroup45Widget3.dart';

/* Frame Pesanan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPesananWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 54.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 20.0,
                child: GeneratedRectangle2Widget7(),
              ),
              Positioned(
                left: 27.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 22.0,
                child: GeneratedPESANANWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget10(),
              ),
              Positioned(
                left: 20.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget10(),
              ),
              Positioned(
                left: 20.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget10(),
              ),
              Positioned(
                left: 20.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget9(),
              ),
              Positioned(
                left: 20.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget9(),
              ),
              Positioned(
                left: 20.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup45Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget16(),
              ),
              Positioned(
                left: 320.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle30Widget6(),
              )
            ]),
      ),
    ));
  }
}
