import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedGroup39Widget7.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedRectangle30Widget2.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedGroup44Widget6.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedGroup41Widget7.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedRectangle3Widget12.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedGroup43Widget6.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget2/generated/GeneratedGroup40Widget7.dart';

/* Frame Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 714.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 190.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget12(),
              ),
              Positioned(
                left: 320.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle30Widget2(),
              ),
              Positioned(
                left: 60.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 20.0,
                child: GeneratedFrame1Widget(),
              )
            ]),
      ),
    ));
  }
}
