import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle10Widget23.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle10Widget26.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedBeliSekarangWidget4.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle15Widget4.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRp1370000Widget6.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle10Widget27.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedALEXWidget6.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedUnitlaciputih36x70cmWidget6.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa3.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRincianProdukWidget5.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle9Widget8.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle1Widget12.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedPetunjukPerawatanWidget5.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle10Widget24.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle14Widget7.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedRectangle10Widget25.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedPRODUKWidget3.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget2/generated/GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla3.dart';

/* Frame Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProdukWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 732.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 24.0,
                child: GeneratedRp1370000Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 32.0,
                child: GeneratedRectangle14Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle1Widget12(),
              ),
              Positioned(
                left: 39.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 250.0,
                child: GeneratedRectangle9Widget8(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget23(),
              ),
              Positioned(
                left: 43.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget24(),
              ),
              Positioned(
                left: 65.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget25(),
              ),
              Positioned(
                left: 87.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget26(),
              ),
              Positioned(
                left: 110.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget27(),
              ),
              Positioned(
                left: 104.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 21.0,
                child: GeneratedBeliSekarangWidget4(),
              ),
              Positioned(
                left: 302.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 28.0,
                child: GeneratedRectangle15Widget4(),
              ),
              Positioned(
                left: 21.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedRincianProdukWidget5(),
              ),
              Positioned(
                left: 21.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 87.0,
                child:
                    GeneratedBahandasarDepanParticleboardCatakrilikKertasfoilTepipla3(),
              ),
              Positioned(
                left: 20.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedALEXWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 20.0,
                child: GeneratedUnitlaciputih36x70cmWidget6(),
              ),
              Positioned(
                left: 21.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 53.0,
                child:
                    GeneratedUntukkualitasmaksimalkencangkankembalisekrupbilaperluLa3(),
              ),
              Positioned(
                left: 21.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 20.0,
                child: GeneratedPetunjukPerawatanWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedPRODUKWidget3(),
              )
            ]),
      ),
    ));
  }
}
