import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedGroup40Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedDISKON15Widget.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedGroup41Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedGroup43Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedGroup39Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedDISKON10Widget.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedDISKONWidget.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedGroup44Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/mobileapp/generatedpromowidget/generated/GeneratedDISKON5Widget.dart';

/* Frame Promo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPromoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 19.0,
                child: GeneratedDISKON5Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 19.0,
                child: GeneratedDISKON10Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 19.0,
                child: GeneratedDISKON15Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 22.0,
                child: GeneratedDISKONWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup45Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget2(),
              )
            ]),
      ),
    ));
  }
}
