import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedKodePOSWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/Generated1234Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedJlMerdekaGg1No123Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedEditProfileWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedKelurahanWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedDHENIRAWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedJawaBaratWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedNomorHP083198Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedKotaWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedAlamatWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedSamaanWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedDheniragmailcomWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedKecamatanWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedKlojenWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedBogorWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedProvinsiWidget.dart';
import 'package:flutterapp/mobileapp/generatedprofilwidget/generated/GeneratedRectangle3Widget.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 23.0,
                child: GeneratedAlamatWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 20.0,
                child: GeneratedJlMerdekaGg1No123Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedJawaBaratWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 23.0,
                child: GeneratedProvinsiWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 23.0,
                child: GeneratedKotaWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 20.0,
                child: GeneratedBogorWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 20.0,
                child: GeneratedKlojenWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 20.0,
                child: GeneratedSamaanWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 20.0,
                child: Generated1234Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 20.0,
                child: GeneratedKodePOSWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 23.0,
                child: GeneratedKelurahanWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 18.0,
                child: GeneratedEditProfileWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 26.0,
                child: GeneratedDHENIRAWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 22.0,
                child: GeneratedDheniragmailcomWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 20.0,
                child: GeneratedNomorHP083198Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 23.0,
                child: GeneratedKecamatanWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget(),
              )
            ]),
      ),
    ));
  }
}
