import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget/generated/GeneratedKERANJANGWidget.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget/generated/GeneratedGroup40Widget.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/mobileapp/generatedpesananwidget/generated/GeneratedGroup43Widget.dart';

/* Frame Pesanan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPesananWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 22.0,
                child: GeneratedKERANJANGWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 75.0,
                child: GeneratedGroup44Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 75.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget1(),
              )
            ]),
      ),
    ));
  }
}
