import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRincianProdukWidget3.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedPetunjukPerawatanWidget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle10Widget13.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle10Widget15.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle10Widget16.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedALEXWidget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle9Widget4.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedBeliSekarangWidget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle3Widget14.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle10Widget14.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRincianProdukWidget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRp1370000Widget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle30Widget4.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle14Widget4.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedUnitlaciputih36x70cmWidget2.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedPetunjukPerawatanWidget3.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle10Widget12.dart';
import 'package:flutterapp/mobileapp/generatedprodukwidget1/generated/GeneratedRectangle57Widget.dart';

/* Frame Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProdukWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 704.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 24.0,
                child: GeneratedRp1370000Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 32.0,
                child: GeneratedRectangle14Widget4(),
              ),
              Positioned(
                left: 43.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 250.0,
                child: GeneratedRectangle9Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget12(),
              ),
              Positioned(
                left: 43.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget13(),
              ),
              Positioned(
                left: 65.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget14(),
              ),
              Positioned(
                left: 87.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget15(),
              ),
              Positioned(
                left: 110.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle10Widget16(),
              ),
              Positioned(
                left: 104.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 21.0,
                child: GeneratedBeliSekarangWidget2(),
              ),
              Positioned(
                left: 302.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 28.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 90.0,
                child: GeneratedRectangle57Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 58.0,
                child: GeneratedRectangle58Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 20.0,
                child: GeneratedRincianProdukWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 87.0,
                child: GeneratedRincianProdukWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedALEXWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 20.0,
                child: GeneratedUnitlaciputih36x70cmWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 631.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 53.0,
                child: GeneratedPetunjukPerawatanWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 20.0,
                child: GeneratedPetunjukPerawatanWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget14(),
              ),
              Positioned(
                left: 320.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle30Widget4(),
              )
            ]),
      ),
    ));
  }
}
