import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedframe2widget/generated/GeneratedGroup69Widget1.dart';

/* Frame Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 236.0,
      height: 95.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 236.0,
              height: 95.0,
              child: GeneratedGroup69Widget1(),
            )
          ]),
    ));
  }
}
