import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhistorypembelianwidget/generated/GeneratedGroup40Widget2.dart';
import 'package:flutterapp/mobileapp/generatedhistorypembelianwidget/generated/GeneratedGroup41Widget2.dart';
import 'package:flutterapp/mobileapp/generatedhistorypembelianwidget/generated/GeneratedGroup39Widget2.dart';
import 'package:flutterapp/mobileapp/generatedhistorypembelianwidget/generated/GeneratedHISTORYPEMBELIANWidget.dart';
import 'package:flutterapp/mobileapp/generatedhistorypembelianwidget/generated/GeneratedRectangle3Widget5.dart';

/* Frame History Pembelian
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryPembelianWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 19.0,
                child: GeneratedHISTORYPEMBELIANWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 75.0,
                child: GeneratedGroup39Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 75.0,
                child: GeneratedGroup40Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 75.0,
                child: GeneratedGroup41Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget5(),
              )
            ]),
      ),
    ));
  }
}
