import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget1/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/mobileapp/generatedhomepagewidget1/generated/GeneratedGroup50Widget1.dart';

/* Frame Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 706.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 638.0,
                child: GeneratedGroup50Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 20.0,
                child: GeneratedGroup68Widget(),
              )
            ]),
      ),
    ));
  }
}
