import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedRectangle27Widget16.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedRectangle27Widget17.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedRectangle28Widget6.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedRectangle29Widget6.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedLupaKataSandiWidget2.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedEmailWidget13.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedLoginWidget6.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedBatalWidget5.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedLOGINWidget2.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedPasswordWidget6.dart';
import 'package:flutterapp/mobileapp/generatedloginwidget5/generated/GeneratedRectangle1Widget11.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 24.0,
                child: GeneratedEmailWidget13(),
              ),
              Positioned(
                left: 30.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle27Widget16(),
              ),
              Positioned(
                left: 30.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle27Widget17(),
              ),
              Positioned(
                left: 30.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 24.0,
                child: GeneratedPasswordWidget6(),
              ),
              Positioned(
                left: 30.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 30.0,
                child: GeneratedRectangle28Widget6(),
              ),
              Positioned(
                left: 190.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 30.0,
                child: GeneratedRectangle29Widget6(),
              ),
              Positioned(
                left: 237.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedLoginWidget6(),
              ),
              Positioned(
                left: 79.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 26.0,
                child: GeneratedBatalWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle1Widget11(),
              ),
              Positioned(
                left: 30.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 26.0,
                child: GeneratedLOGINWidget2(),
              ),
              Positioned(
                left: 118.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 21.0,
                child: GeneratedLupaKataSandiWidget2(),
              )
            ]),
      ),
    ));
  }
}
