import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedGroup63Widget.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedRectangle3Widget17.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedALEXWidget3.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedUnitlaciputih36x70cmWidget3.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedRectangle30Widget7.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedPRODUKWidget.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedRp1370000Widget3.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedRectangle9Widget5.dart';
import 'package:flutterapp/mobileapp/generatedorderanwidget1/generated/GeneratedGroup64Widget.dart';

/* Frame Orderan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrderanWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1171.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1171.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 81.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 250.0,
                              child: GeneratedRectangle9Widget5(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 22.0,
                              child: GeneratedPRODUKWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 391.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 24.0,
                              child: GeneratedRp1370000Widget3(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 24.0,
                              child: GeneratedALEXWidget3(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 20.0,
                              child: GeneratedUnitlaciputih36x70cmWidget3(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 811.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 345.0,
                              child: GeneratedGroup63Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 25.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedRectangle3Widget17(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 541.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 250.0,
                              child: GeneratedGroup62Widget(),
                            ),
                            Positioned(
                              left: 320.0,
                              top: 25.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedRectangle30Widget7(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 421.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 100.0,
                              child: GeneratedGroup64Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
