import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedPesananWidget1.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedRiwayatPembelianWidget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedKategoriWidget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedKeranjangWidget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedRectangle3Widget7.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedDiskonWidget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/mobileapp/generatedpengaturanwidget/generated/GeneratedRectangle2Widget.dart';

/* Frame Pengaturan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPengaturanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 706.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 20.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 90.00000762939453,
                height: 30.0,
                child: GeneratedGroup37Widget(),
              ),
              Positioned(
                left: 321.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle3Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 638.0,
                child: GeneratedGroup50Widget(),
              ),
              Positioned(
                left: -12.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 706.0,
                child: GeneratedRectangle55Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 20.0,
                child: GeneratedRectangle61Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 20.0,
                child: GeneratedRiwayatPembelianWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 23.0,
                child: GeneratedPesananWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 23.0,
                child: GeneratedDiskonWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 23.0,
                child: GeneratedKategoriWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 23.0,
                child: GeneratedKeranjangWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 1.0,
                child: GeneratedLine12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 1.0,
                child: GeneratedLine16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 1.0,
                child: GeneratedLine13Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 209.99993896484375,
                height: 1.0,
                child: GeneratedLine14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 211.0023651123047,
                height: 1.0,
                child: GeneratedLine15Widget(),
              ),
              Positioned(
                left: 170.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle63Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 15.0,
                child: GeneratedGroup70Widget(),
              )
            ]),
      ),
    ));
  }
}
